#!/bin/ash

dev=$DEVICENAME
echo "$DEVICENAME" | grep -q 'sd[a-z][1-9]'
if [ $? -ne 0 ]; then
        exit 0
fi
case "$ACTION" in
    add)
        mkdir -p /mnt/$dev
        mount -o nls=utf8,rwx /dev/$dev /mnt/$dev
        if [ $? -ne 0 ]; then
            mount -o rwx /dev/$dev /mnt/$dev
        fi
        ;;
    remove)
        umount /mnt/$dev && rm -r /mnt/$dev
        ;;
esac
